Hyundai-Kia-Connect/hyundai_kia_connect_api

hyundai_kia_connect_api/ApiImpl.py
hyundai_kia_connect_api/KiaUvoAPIUSA.py
hyundai_kia_connect_api/VehicleManager.py

Kia USA has a vehicle specific one time use key.  This will update this in vehicle and also add new cars that may be found.  Other option may be make get_vehicles work this way, need to also add a delete.  Challenge with that is then get_vehicles will be called each token refresh including for APIs that don't need it.

fix(USA Kia): Refresh key for vehicles on expiry

---

hyundai_kia_connect_api/HyundaiBlueLinkAPIUSA.py

Fixes #43 - read vehicle ID from the right place.
I haven't been able to figure out how to get tests to run, so there aren't any tests or anything, but I can verify that this works (for me, at least) and lets me read data from my car.

fix(USA Hyundai): HyundaiBlueLinkAPIUSA.get_location

---

hyundai_kia_connect_api/KiaUvoAPIUSA.py

In the US Kia vehicle and UVO app, the next step below 62 is "LOW" and the next step above 82 is "HIGH". So if you try to set the climate to an actual number lower than 62 or higher than 82, it causes an error that leads to the engine and the rear defroster coming on, but the AC does not. I don't know of an easy way to change the service call itself to accept numbers and also the words "LOW" and "HIGH", so adding the logic check to the API accounts for that and prevents the error.

fix(US Kia): Correct temperature setting when starting climate

---

hyundai_kia_connect_api/KiaUvoApiEU.py

Appears to be an error where EU Kia lock status is inverted

fix(EU): inverted lock status

---

hyundai_kia_connect_api/KiaUvoApiEU.py

EU Steering wheel heat comes as int yet I believe is boolean. Not sure why they did this. 
https://github.com/fuatakgun/kia_uvo/issues/291#issuecomment-1036271960

fix(EU): Steering Wheel Heat

---

hyundai_kia_connect_api/KiaUvoApiEU.py

Currently if called with debug enabled it does have any record of it being called logged.

fix(EU): Added logging to Charge Limits

---

hyundai_kia_connect_api/KiaUvoApiEU.py

Force update deletes all values since it actually doesn't hold its items in "vehicleStatus". Should be the final PR to resolve: https://github.com/Hyundai-Kia-Connect/kia_uvo/issues/468

fix(EU): Force Update Blanks Values

---

hyundai_kia_connect_api/KiaUvoApiEU.py
hyundai_kia_connect_api/const.py

Let me know thoughts on this.   Essentially we are going to throw this on many cars so will have many reports of issues where this is normal for cars that don't offer it.   
I am torn between the approach in this PR vs checking for a value with an if statement within the call. If no driving info passed just log it as warning or debug as that is normal.  That would let the exception level still throw on unknown issues. 
Trying to resolve this: 
https://github.com/Hyundai-Kia-Connect/kia_uvo/issues/472

fix(EU): Get Driving for unsupported cars

---

hyundai_kia_connect_api/HyundaiBlueLinkAPIUSA.py

Removed the not status from is_locked to correct inversion of status.
Tested by changing kia_uvo lock.py with:
```python
@property
def is_locked(self):
not_locked = not getattr(self.vehicle, "is_locked")
return not_locked
```
Found the upstream status and changed the toggle. This was also present in v1.X, which I corrected there as well.

Removed not from is_locked

---

hyundai_kia_connect_api/KiaUvoApiCA.py
hyundai_kia_connect_api/Vehicle.py

In CA api, store timezone per vehicle to avoid issues for a user who has two vehicles on different timezones.
Tested and working as expected for me.

fix(CA): timezone stored per vehicle

---

README.rst
hyundai_kia_connect_api/HyundaiBlueLinkAPIUSA.py
hyundai_kia_connect_api/KiaUvoAPIUSA.py
hyundai_kia_connect_api/KiaUvoApiCA.py
hyundai_kia_connect_api/KiaUvoApiEU.py
hyundai_kia_connect_api/VehicleManager.py

Implemented issue:  Android Bluelink App language is reset to English when using hyundai_kia_connect_api #145 
Added optional language to constructor of VehicleManager, defaults to "en" and pass them to the implementation classes constructor and use the language where appropriate. 
Note that I could only test KiaUvoApiEU.py.

feat(EU): Android Bluelink App language reset to English #145

---

hyundai_kia_connect_api/KiaUvoApiEU.py
hyundai_kia_connect_api/exceptions.py

When two cars exist in the EU and a car has been offline for an extended period both cars fail due to no data for a single car.
https://github.com/Hyundai-Kia-Connect/kia_uvo/issues/514

fix(EU): Car Offline

---

hyundai_kia_connect_api/Vehicle.py

Added getter location_last_updated_at for protected instance vehicle._location_last_set_time
This solves issue #234 
````
@property
def location_last_updated_at(self):
"""
return last location datetime.
last_updated_at and location_last_updated_at can be different.
The newest of those 2 can be computed by the caller.
"""
return self._location_last_set_time
````

Feat: getter for vehicle._location_last_set_time issue #234

---

README.rst
hyundai_kia_connect_api/ApiImpl.py
hyundai_kia_connect_api/KiaUvoApiEU.py
hyundai_kia_connect_api/Vehicle.py
hyundai_kia_connect_api/VehicleManager.py
hyundai_kia_connect_api/utils.py

General:
- I developed with Visual Studio Code on Windows 10 with pylint and flake8 enabled and black formatting at save of file
- For touched files, added as first line a # pylint:disable warnings, so I could concentrate on the real warnings
- Some warnings I did solve
- Maybe something in the future to solve pylint/flake8 warnings or ignore at place where it occurs?
- Feel free to remove the first lines with # pylint:disable
- Sometimes black reformatted some lines
README.rst:
- added usage information of the trip info methods/fields
ApiImpl.py:
- line 13: removed unused imports
- added methods update_month_trip_info and update_day_trip_info
KiaUvoApiEU.py:
- added imports for new dataclasses
- line 207: ex1 was not used, so removed
- line 218 and 221: token_type not used, so replaced …

feat(EU): TripReports

---

hyundai_kia_connect_api/KiaUvoApiEU.py

Remove the logic to combat bad data.  This only existed in a single EU version that has since been resolved.

fix(EU):  Remove Odometer Logic

---

hyundai_kia_connect_api/KiaUvoApiEU.py
hyundai_kia_connect_api/exceptions.py

It appears that in KiaUvoApiEU.py errorcode 5031: "Unavailable remote control - Service Temporary Unavailable" is mapped to the generic APIError:
````
"5031": APIError,
````
I expected a specific exception in exception.py, e.g. ServiceTemporaryUnavailable so I could catch that specific exception too and could add to my code:
````
except exceptions.ServiceTemporaryUnavailable as ex:
retries = handle_exception(ex, retries)
````

feat(EU): Missing ServiceTemporaryUnavailable Exception in KiaUvoApiEU.py #267

---

hyundai_kia_connect_api/ApiImpl.py
hyundai_kia_connect_api/HyundaiBlueLinkAPIUSA.py
hyundai_kia_connect_api/KiaUvoAPIUSA.py
hyundai_kia_connect_api/KiaUvoApiCA.py
hyundai_kia_connect_api/KiaUvoApiEU.py
hyundai_kia_connect_api/VehicleManager.py
hyundai_kia_connect_api/const.py

This PR is a follow up from https://github.com/Hyundai-Kia-Connect/hyundai_kia_connect_api/pull/195
I implemented the following changes:
- EU API support: check last action with the /notifications endpoint
- EU API support: modify action functions to return action ID
- rename `check_last_action_status` to `check_action_status`
- synchronous checks (detailed below)
The function takes 2 new arguments:
- `synchronous` (bool): if True, then poll the API until a final state (success/fail/timeout) is returned. if False, then perform just 1 request and return the status immediately, even if still pending. This gives flexibility to developers: they can rely on the library to return a final state, or they can implement this logic at a higher level if they prefer.
-  `timeout` (int, seconds): if …

feat(EU): check action status

---

hyundai_kia_connect_api/HyundaiBlueLinkAPIUSA.py

I recently got a new Hyundai (in the US) and found this library via the `kia_uvo` Home Assistant integration. I found that the BlueLink data was often very stale, which makes sense given the lack of a force-refresh implementation. I've taken a shot at adding that to the `HyundaiBlueLinkAPIUSA` file. I incorporated some of the changes from #244 as part of a bit of refactoring of the various internal API call methods.
Fixes #31 
I tested this by:
- Setting up a Home Assistant dev environment
- Manually installing the `kia_uvo` integration
- Manually installing this library in the HA virtualenv with `pip3 install -e ../hyundai_kia_connect_api`
- Starting HA with pip skipping this library with `hass --skip-pip-packages hyundai-kia-connect-api -c config`
- Enabling debug logging per the docs …

USA Hyundai force refresh

---

hyundai_kia_connect_api/ApiImpl.py
hyundai_kia_connect_api/HyundaiBlueLinkAPIUSA.py
hyundai_kia_connect_api/KiaUvoAPIUSA.py
hyundai_kia_connect_api/KiaUvoApiCA.py
hyundai_kia_connect_api/KiaUvoApiEU.py
hyundai_kia_connect_api/Token.py
hyundai_kia_connect_api/VehicleManager.py
hyundai_kia_connect_api/__init__.py
hyundai_kia_connect_api/const.py
hyundai_kia_connect_api/exceptions.py

Issue root cause described here:
https://github.com/ZuinigeRijder/hyundai_kia_connect_monitor/issues/48#issuecomment-1436588493
The root cause is in the hyundai_kia_connect_api library.
In Vehicle.py _location_last_set_time is not correctly filled, only for KiaUvoApiEU.py this is done correctly.
You see the missing conversion to a datetime in HyundaiBlueLinkAPIUSA.py.
````
vehicle.location = (
get_child_value(state, "vehicleStatus.vehicleLocation.coord.lat"),
get_child_value(state, "vehicleStatus.vehicleLocation.coord.lon"),
get_child_value(state, "vehicleStatus.vehicleLocation.time"),
)
````
The last statement should be converted to a datetime, e.g. with get_last_updated_at.
Note that the same is wrong for KiaUvoAPIUSA.py and KiaUvoApiCA.py.
here are 2 problems in get_last_updated_at for …

fix: location_last_updated_at

---

hyundai_kia_connect_api/HyundaiBlueLinkAPIUSA.py
hyundai_kia_connect_api/KiaUvoAPIUSA.py
hyundai_kia_connect_api/KiaUvoApiEU.py
hyundai_kia_connect_api/Vehicle.py

HyundaiBlueLinkAPIUSA.py always fills location with cached vehicle location, also when findMyCar is called. This results in the situation that _location_last_set_time is never filled with a datetime for the Bluelink USA implementation!
Another problem encountered is the inconsistent filling of vehicle.timezone. This is only filled by KiaUvoApiCA.py in the constructor of Vehicle. 
Issue analyzed here:
https://github.com/ZuinigeRijder/hyundai_kia_connect_monitor/issues/48#issuecomment-1447709689
Vehicle.timezone is not consistent used. Only in KiaUvoApiCA.py this is set, in the other implementations HyundaiBlueLinkAPIUSA.py, KiaUvoApiEU.py and KiaUvoAPIUSA.py these are NOT initialized when Vehicle is instantiated, while internally they use UTC.
Easy fix is changing the default timezone in …

fix(BluelinkUSA): always cached location used

---

hyundai_kia_connect_api/KiaUvoApiEU.py
setup.py

I updated the auth_client_id (sniffed from the iPhone app).
It fixes login for my account that was created in late 2022. issue #309 
If I understand correctly, accounts created before 2020 were UVO accounts and were merged at some point into a global Kia account.
The previous fix works with pre-2020 accounts but not post-2020 accounts.
This change should fix login for post-2020 accounts 🤞 
If someone with a pre-2020 account can test it to see if it causes any regressions, that'd be great.

#309: Kia (EU): fix login for additional cases

---

hyundai_kia_connect_api/KiaUvoApiEU.py

Should fix https://github.com/Hyundai-Kia-Connect/hyundai_kia_connect_api/issues/354
Tests:
No regression on my Kia EU account.
Needs a test for Hyundai.

fix(eu): notifications: use GCM for hyundai and APNS for Kia (#354)

---

hyundai_kia_connect_api/KiaUvoApiEU.py
hyundai_kia_connect_api/exceptions.py

This will do a few things:
1. Log the error code itself to make this easier for me in the future.
2. Throw an device ID exception which is a child of Authentication Error.   My understanding is when a device ID error occurs we should re-login.  The Home assistant integration does this if it catches auth error.  So this will automatically take care of it in theory.  I can't test as I am not in EU. This should be removed in the future if we find out how to not invalidate the device id. 
https://github.com/Hyundai-Kia-Connect/kia_uvo/issues/672

fix(EU): Auth error on bad device id

---

hyundai_kia_connect_api/HyundaiBlueLinkAPIUSA.py

Update SSL context to enable ssl.OP_LEGACY_SERVER_CONNECT, which isn't in Python yet (see python/cpython#89051, it'll be in 3.12), but in OpenSSL its value is 0x4 in the bitfield.
Fixes Hyundai-Kia-Connect/kia_uvo#678 and Hyundai-Kia-Connect/kia_uvo#679.
Once this is merged, you'll need to do a version bump of this and then bump the version of the required API in Hyundai-Kia-Connect/kia_uvo, obviously.

Set ssl.OP_LEGACY_SERVER_CONNECT in order to be able to connect to unsafe SSL servers that OpenSSL 3.0.0 prohibits by default now.

---

hyundai_kia_connect_api/KiaUvoApiAU.py

Fixes the missing sensors - looks like Australia's API response skips the extra `status` layer. 
I've rewrapped it at the call site instead because I'm looking to start sharing the vehicle parsing code across regions instead. 
With this I'm now able to get the battery level correctly :)

fix: add wrapping status layer for Australia vehicle parsing

---

hyundai_kia_connect_api/VehicleManager.py

This change enables handling of Genesis vehicles in the USA region to be handled by HyundaiBlueLinkAPIUSA module. In limited testing this was successful in retrieving vehicle details.

Enable Genesis path for USA

---

hyundai_kia_connect_api/KiaUvoApiEU.py

Rather than relying on am/pm parsing (which can fail based on locale) rather add 12h using the datetime module.
I hit this when using this module embedded in a tiny [Rust application](https://gitlab.gnome.org/guidog/phosh-ev/)
with pyo3.
Thanks a lot for providing this very useful module!

fix(eu): Add 12h using datetime

---

hyundai_kia_connect_api/KiaUvoApiEU.py

total power consumed is obtained from drivingInfo, not drivingInfoDetail

fix(EU): correction to get total power consumed from driving info

---

hyundai_kia_connect_api/HyundaiBlueLinkAPIUSA.py

Align URLs. This is first attempt to align to #369

fix(USA): Hyundai EV Start Stop

---

hyundai_kia_connect_api/Vehicle.py
hyundai_kia_connect_api/utils.py

Class Vehicle in Vehicle.py declares _odometer as a float (so the intention and users of the API are expecting a float):
_odometer: float = None
It appears that _odometer als can be a string with a float or int embedded inside the string. At least this is the case with HyundaiBlueLinkAPIUSA.py. I do not know if other classes also can deliver a string, so added this in the Vehicle class, when assigning the instance value. 
To avoid the callers of the API to handle these strange deviations, it is better that the API convert safely to a float, when a string is encountered instead of a float.
See also this issue: Vehicle.odometer is string instead of float for HyundaiBlueLinkAPIUSA.py #433

fix: vehicle.odometer can be float-string instead of float

---

hyundai_kia_connect_api/HyundaiBlueLinkAPIUSA.py
hyundai_kia_connect_api/KiaUvoAPIUSA.py
hyundai_kia_connect_api/KiaUvoApiAU.py
hyundai_kia_connect_api/KiaUvoApiCA.py
hyundai_kia_connect_api/KiaUvoApiCN.py
hyundai_kia_connect_api/KiaUvoApiEU.py

Implemented support for the field brake_fluid_warning_is_on which was already present in Vehicle but not filled by the APIs.
I tested it with my EU car and it seems to work properly.

Support for brake_fluid_warning_is_on

---

hyundai_kia_connect_api/KiaUvoAPIUSA.py

if front or rear seat is not set, it currently fails with no value defined. setting a default value of 0 to fix this issue.
i also made it easier to read for determining what is ventilated vs heated.

fix(USA): default value 0 for heatVentType

---

hyundai_kia_connect_api/KiaUvoAPIUSA.py

options value passed is not the expected value by the api. creating a new mapping with the values adjusted to what is expected.

fix(USA): remap seat values

---

hyundai_kia_connect_api/KiaUvoAPIUSA.py
hyundai_kia_connect_api/KiaUvoApiCA.py
hyundai_kia_connect_api/KiaUvoApiCN.py
hyundai_kia_connect_api/KiaUvoApiEU.py
hyundai_kia_connect_api/const.py

fix: Add the token lifetime to `const.py` and use the value across all API endpoints.

fix: Add login token lifetime to consts and use it in all API clients

---

hyundai_kia_connect_api/HyundaiBlueLinkAPIUSA.py

The US version of the MyHyundai app shows some details about the most recent trips; extract and expose this.
This change uses the same API call to pull the trip data and add to `vehicle.daily_stats`. The data in the Hyundai API response matches exactly with the existing EU `Vehicle.DailyDrivingStats`, so I reused that data structure despite the slight name difference.
A simple example:
```python
#!/usr/bin/env python3
from hyundai_kia_connect_api import *
import pprint
vm = VehicleManager(region=3, brand=2, username="me@example.com", password="hunter2", pin="1234")
vm.check_and_refresh_token()
vm.update_all_vehicles_with_cached_state()
for v in vm.vehicles:
pprint.pprint(vm.vehicles[v].name)
for s in vm.vehicles[v].daily_stats:
distance = (s.distance if s.distance > 0 else 1)
whpmi = …
```

feat(USA): Expose EV Trip Details (#473)

---

hyundai_kia_connect_api/KiaUvoApiEU.py

Currently not tested, just looked at the json data as attached
[kona2024data.txt](https://github.com/Hyundai-Kia-Connect/hyundai_kia_connect_api/files/14166280/kona2024data.txt)

fix: support air_temperature with ccs2

---

hyundai_kia_connect_api/KiaUvoApiEU.py

For non cc2 the behaviour was that the daily stats were sorted by the bluelink/Connect server:
- increasing yyyymmss
- decreasing hhmmss
For cc2 the order is undefined. Fixed by always sorting when the Bluelink/Connect server returns the daily stats.
This will solve the issue: [Daily driving stats not sorted on date #820](https://github.com/Hyundai-Kia-Connect/kia_uvo/issues/820)
Also a minor style change and flake line length suppression warnings.

fix(EU): sort daily stats for same behaviour between cc2 and non-cc2

---

hyundai_kia_connect_api/KiaUvoApiEU.py

A Kona Model 2024 user complained about the non-filled Vehicle.ev_total_driving_range. In the debug log I do not see this information for this cc2 model. When it is a pure EV, the Vehicle.ev_total_driving_range should be identical to the Vehicle.total_driving_range, as is with non-cc2 EU API. 
So for pure EV, this can be fixed for cc2 models (identical behaviour for cc2 and non-cc2 users of the API), to fill Vehicle.ev_total_driving_range with Vehicle.ev_total_driving_range. For non pure EV's (e.g. PHEV) it should be investigated further how to get the Vehicle.ev_total_driving_range (TODO kept).

fix(EU): fill Vehicle.ev_driving_range with Vehicle.total_driving_range for cc2 for pure EV to have similar behaviour for non-cc2 

---

hyundai_kia_connect_api/KiaUvoApiEU.py

Typo in resCode that didn't allow actual response from server to be displayed when not one of the known error codes.

fix: Typo in resCode, written as rescode

---

hyundai_kia_connect_api/KiaUvoApiEU.py

For vechicles lacking CalculativeOdo in the eu, this change means that it will silently continue and not throw as is in the current version. 
Fixes the exception mentioned in https://github.com/Hyundai-Kia-Connect/kia_uvo/issues/842.
Note, if this key is actually suposed to be present for all vechicles (including phev which seems to be the issue here), then this will just hush the exception and obv not fix the main issue.

fix: step over calculativeodo if not found or zero, to avoid exceptions.

---

hyundai_kia_connect_api/KiaUvoAPIUSA.py

I looked into what was being sent on the web portal for USA and noticed that remoteClimate only had temp and unit, I rearranged that on my version of home assistant and climate action started working again so I am submitting this pull request with the rearranged body.

fix: kia usa climate start

---

hyundai_kia_connect_api/ApiImpl.py
hyundai_kia_connect_api/ApiImplType1.py
hyundai_kia_connect_api/KiaUvoApiEU.py
hyundai_kia_connect_api/Vehicle.py

Hi! I noticed this feature missing and I have a need for it (including others apparently: https://github.com/Hyundai-Kia-Connect/kia_uvo/issues/864).
I sniffed the traffic on my EU app, so I don't know if other regions also have support for this, the above mentioned issue has screenshots in German so that is EU too :)
With this implemented we can set the charging current to 60%, 90% or 100%

feat(EU): Support setting the charging current

---

hyundai_kia_connect_api/HyundaiBlueLinkAPIUSA.py

The Bluelink API returns AC and DC charge limit data for EVs, similar to Kia's API. This change selects for it identically to KiaUvoAPIUSA.py, but with the correct object path for Bluelink's API response.

feat: Add AC and DC charge limits for Hyundai USA Bluelink

---

hyundai_kia_connect_api/Vehicle.py
hyundai_kia_connect_api/utils.py

The Bluelink/Connect server does return for some regions the UTC timezone and for other (at least for Europe) the local timezone. To have a consistent behavior for hyundai_kia_connect_api, the datetime is always converted to the local timezone, like in Europe region.
This will solve issue IONIQ 5 Canada Region Timezone wrong #561

fix: Convert to local timezone for all regions to have consistent datetime

---

hyundai_kia_connect_api/KiaUvoAPIUSA.py

Hi.  Sorry for the out of the blue PR from a random contributor on the internet.
Please see https://github.com/Hyundai-Kia-Connect/kia_uvo/issues/913
This PR sets the 0x4 flag on the SSL context for the KIA USA SSL adapter.
Thank you for your great work!

fix: SSL error for USA KIA

---

README.rst
hyundai_kia_connect_api/ApiImpl.py
hyundai_kia_connect_api/ApiImplType1.py
hyundai_kia_connect_api/HyundaiBlueLinkAPIUSA.py
hyundai_kia_connect_api/KiaUvoApiAU.py
hyundai_kia_connect_api/KiaUvoApiCN.py
hyundai_kia_connect_api/KiaUvoApiEU.py
hyundai_kia_connect_api/Vehicle.py
hyundai_kia_connect_api/VehicleManager.py
hyundai_kia_connect_api/utils.py

Only KiaUvoApiEU.py was sorting Vehicle.daily_stats, Vehicle.month_trip_info and Vehicle.day_trip_info, other implementations did not.
Moved the sorting to Vehicle in each setter.
Changed the Europe only comment.
Fixed or suppressed flake and lint warnings.
This partly solves (problem 1) this issue: https://github.com/Hyundai-Kia-Connect/hyundai_kia_connect_api/issues/617

fix: sort daily_stats for all implementations in setter of Vehicle.daily_stats

---

hyundai_kia_connect_api/KiaUvoApiCA.py
hyundai_kia_connect_api/utils.py

The Canadian website (and surely others) sometimes returns a decimal for temperatures. Since the expected value is an integer, it crashes everything. See crash report below.
> Failed setup, will retry: Config Not Ready: Error communicating with API: Traceback (most recent call last): File "/config/custom_components/kia_uvo/coordinator.py", line 126, in _async_update_data await self.hass.async_add_executor_job( File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run result = self.fn(*self.args, **self.kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.12/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 115, in check_and_force_update_vehicles self.update_vehicle_with_cached_state(vehicle_id) File …

fix: Removed possible decimals from get_hex_temp_into_index

---

hyundai_kia_connect_api/HyundaiBlueLinkAPIUSA.py
hyundai_kia_connect_api/Vehicle.py

For Europe trip info duration and idle time are in minutes. For HyundaiBlueLinkAPIUSA.py the Bluelink API returns it in seconds. Now the seconds are converted to minutes for HyundaiBlueLinkAPIUSA.py.
[See this discussion](https://github.com/ZuinigeRijder/hyundai_kia_connect_monitor/discussions/68#discussioncomment-10714627).
The changes [have been tested here](https://github.com/ZuinigeRijder/hyundai_kia_connect_monitor/discussions/68#discussioncomment-10722153).

fix(USA): fix USA Hyundai duration idle times

---

hyundai_kia_connect_api/KiaUvoApiEU.py

Server rejects schedule charge/climate request when day is empty

fix(EU): update default of ScheduleChargingClimateRequestOptions::DepartureOptions::days to non-empty to avoid API error

---

hyundai_kia_connect_api/KiaUvoAPIUSA.py
hyundai_kia_connect_api/KiaUvoApiCA.py

This is due to requests.Session() call in the constructor that would load the TLS certificates, block the main loop.
Fix a flake8 line too line warning.
Fixes #659

fix: stop warning on home assistant startup

---

.gitignore
hyundai_kia_connect_api/__init__.py

Confirmed that kia_uvo only needs the remaining imports. Kept WindowRequestOptions even if it is not used yet.
BREAKING CHANGE: Remove the API implementation from being exported since the user should use VehicleManager().
The goal is to make internal refactoring safer by reducing the risk for future breaking changes.
This make it possible to reduce code duplication in the future.
Add virtualenv items to .gitignore.

chore!: reduce number of exports

---

hyundai_kia_connect_api/HyundaiBlueLinkAPIUSA.py
hyundai_kia_connect_api/Vehicle.py

For Bluelink USA the distance in the Vehicle dailystats is in whole miles and not in one-tenth of miles. However, also the odometer in one-tenth of miles is send when getting the trip details. See [this discussion post](https://github.com/ZuinigeRijder/hyundai_kia_connect_monitor/discussions/68#discussioncomment-10914206).   
> This needs to be solved at HyundaiBlueLinkAPIUSA.py, not in hyundai_kia_connect_monitor. In principle this can be done, by comparing the previous odometer trip with the current. Problem will be the earliest trip, nothing to compare with, so fallback to distance.
> Compute the delta miles from "odometer - previous odometer" and if there is no previous odometer fallback to "distance".
Also changed the typing of distance to float in Vehicle.py. In Europe (and maybe …

feat: Bluelink USA better distance accuracy using odometer, one-tenth of mile

---

hyundai_kia_connect_api/ApiImpl.py
hyundai_kia_connect_api/KiaUvoApiEU.py
hyundai_kia_connect_api/VehicleManager.py
hyundai_kia_connect_api/const.py

prerequisite of https://github.com/Hyundai-Kia-Connect/kia_uvo/issues/966

feat(EU): support valet mode

---

hyundai_kia_connect_api/HyundaiBlueLinkAPIUSA.py
hyundai_kia_connect_api/Vehicle.py

Bluelink in America started supporting the EV charge rate in kW a couple weeks ago.
The JSON exposes two fields named batteryStndChrgPower and batteryDischrgPower whose values appear to be equivalent. I've used StndChrgPower to populate `vehicle.ev_charging_current`.

feat(USA hyundai): Add EV charge rate support

---

hyundai_kia_connect_api/HyundaiBlueLinkApiUSA.py
hyundai_kia_connect_api/KiaUvoApiUSA.py
hyundai_kia_connect_api/VehicleManager.py

The fact that the USA one had "API" ALL CAPS but all others had "Api" really triggered me. This should not be a breaking change because clients use VehiculeManager but there's still a risk.
exceptions.py also use API all caps but that would break clients so this is not changed.

chore(USA): Rename *APIUSA to *ApiUSA

---

hyundai_kia_connect_api/Vehicle.py

This stops exceptions from being raised in Home Assistant as reported at
https://github.com/Hyundai-Kia-Connect/kia_uvo/issues/710#issuecomment-2470834826
This doesn't fix the original reported issue so not closing it.
Note that this happens because
https://github.com/Hyundai-Kia-Connect/kia_uvo/blob/585ff9d56d8617e40787d33f4440ec2e93660b5d/custom_components/kia_uvo/sensor.py#L120
looks at `Vehicule._air_temperature` directly and bypass the property `air_temperature`. It took me a while to realize that.

fix: replace 'OFF' with None

---

hyundai_kia_connect_api/HyundaiBlueLinkApiUSA.py
hyundai_kia_connect_api/KiaUvoApiEU.py
hyundai_kia_connect_api/Vehicle.py
hyundai_kia_connect_api/bluelink.py

ev_charging_current defines the the portion of electric current the vehicle takes from the charger
available options are 1, 2 and 3 which map to 100% and 90% and 60% in kia_uvo
It cannot be used for charging power, which is in (float) kW.
also fixing the json string according to the capture in https://github.com/Hyundai-Kia-Connect/kia_uvo/issues/961

feat: EV charging speed in EU and fix for US

---

.github/ISSUE_TEMPLATE.md
hyundai_kia_connect_api/KiaUvoApiUSA.py

This sets the `heatVentStep` to the appropriate value.  It also does
away with the math on `heatVentLevel`, which I found confusing.  It
now treats the options value more like an enum.
The values are based on the empirical data from
Hyundai-Kia-Connect/kia_uvo#718 and confirmed on my own vehicle.

fix: seat heat/cool settings for USA vehicles

---

hyundai_kia_connect_api/VehicleManager.py

Hello,
This PR adds the ability to call the check_and_force_update_vehicles function for just one specific vehicle.
The reason this is a neccessary feature is that if you have multiple vehicles connected to your account and one of them goes into energy saver mode so that it does not respond to force update requests anymore, these requests fail with an APIError which breaks the vehicles loop so that later vehicles are not queried at all even though they would respond. With the new funtion it is possible to query the vehicles from isolated try blocks so that one failing vehicle does not cause all others to fail too.
Best regards,
Triple-S

feat: Add ability to call check_and_force_update_vehicles function for just one specific vehicle.

---

hyundai_kia_connect_api/KiaUvoApiUSA.py

This is needed for vehicles with multiple heating levels on the
steering wheel.  This doesn't allow for customization of the level
(it's always on high), but it's better than not being set.
Tested to work on a 2024 Kia EV9, but I am unsure if it'll cause
problems on vehicles without multiple levels.

fix: add steeringWheelStep: 2

---

hyundai_kia_connect_api/KiaUvoApiCA.py

Resolve issues with starting climate control due to contract changes and update the payload structure to include seat options for electric vehicles.
```
curl 'https://kiaconnect.ca/tods/api/evc/rfon' \
-H 'Accept: application/json, text/plain, */*' \
-H 'Accept-Language: en-US,en;q=0.9,ar-EG;q=0.8,ar;q=0.7' \
-H 'Cache-Control: no-cache' \
-H 'Connection: keep-alive' \
-H 'Content-Type: application/json;charset=UTF-8' \
-H 'Cookie: remMeCWP=your_email@example.com' \
-H 'Origin: https://kiaconnect.ca' \
-H 'Pragma: no-cache' \
-H 'Referer: https://kiaconnect.ca/remote/' \
-H 'Sec-Fetch-Dest: empty' \
-H 'Sec-Fetch-Mode: cors' \
-H 'Sec-Fetch-Site: same-origin' \
-H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 …
```

fix: climate control functionality for EV vehicles in Canada

---

hyundai_kia_connect_api/KiaUvoApiCA.py

Fixes Hyundai-Kia-Connect/kia_uvo#1002
Caused by #702
This commit addresses the climate control issue as described in [Hyundai-Kia-Connect/kia_uvo#1002](https://github.com/Hyundai-Kia-Connect/kia_uvo/issues/1002). 
The payload for the remote climate control has been reverted for Hyundai and Genesis.

fix: Hyundai (and possibly Genesis) climate control issue

---

hyundai_kia_connect_api/KiaUvoApiCA.py

Updated the login API to v2 and changed the 'From' header from SPA to CWP based on captured traffic between the browser and the mybluelink.ca site. Dropped legacy cipher support. V2 login has a different structure for accesstoken and refresh token, therefore, updated the way to retrive the tokens. 
It seems to be working on my HAOS but might need more testing. It appears that Cloudflare believes part of the request contains a string that triggered its security solution.
Below SS were from the api calling mybluelink.ca
---

fix(CA): fixed the cloudflare 403 issue

---

hyundai_kia_connect_api/ApiImpl.py
hyundai_kia_connect_api/KiaUvoApiCA.py
hyundai_kia_connect_api/VehicleManager.py

close issue: https://github.com/Hyundai-Kia-Connect/kia_uvo/issues/1039
+ Test token before each request. Test by sending a dummy request (Get # of notifications)
+ If the token expires, it will log in again. 
```
2025-02-20 03:50:33.410 DEBUG (SyncWorker_2) [hyundai_kia_connect_api.KiaUvoApiCA] hyundai_kia_connect_api - Test Token Response {"error":{"errorCode":"7403","errorDesc":"Your authentication has expired. Please return to the login page and enter your credentials."},"responseHeader":{"responseCode":1}}
2025-02-20 03:50:33.411 DEBUG (SyncWorker_2) [hyundai_kia_connect_api.VehicleManager] hyundai_kia_connect_api - Refresh token expired
2025-02-20 03:50:33.809 DEBUG (SyncWorker_2) [hyundai_kia_connect_api.KiaUvoApiCA] hyundai_kia_connect_api - Sign In Response …
```

fix: CA new api token expire fix

---

hyundai_kia_connect_api/bluelink.py

Bluelink API responses invalid header when bluelink account pin is entered as integer.
```
requests.exceptions.InvalidHeader: Header part (1234) from ('blueLinkServicePin', 1234) must be of type str or bytes, not <class 'int'>
```
This PR changes the pin datatype to str.

fix: InvalidHeader: Change bluelink pin datatype to str

---

hyundai_kia_connect_api/KiaUvoApiUSA.py

Within the last 24 hours, Kia is no longer allowing the old app headers to log in. By updating the headers to the latest app version and user-agent, we can login again without issue.

fix: Updated headers to latest Kia app version to fix login (US).

---

hyundai_kia_connect_api/ApiImplType1.py

This fixes a key bug that would impact Australia being a +10 offset. I would like eyes on this. Only touches ccs cars since I don't know if offset exists for non ccs cars or if they still live in UTC for data. If someone has a non ccs car would be great to check the data in the API for "offset".
@fuatakgun  could you check if your CCS car now reports offset?

fix: obey ccs timezones

---

hyundai_kia_connect_api/HyundaiBlueLinkApiUSA.py

This should fix the issues in Hyundai-Kia-Connect/kia_uvo#1135. Wasn't sure of the best method to determine when to include the extra options so based it off of `vehicle.generation`. Happy to update if there's a better way to do this but I was able to test successfully with both a 2025 Ioniq 6 (generation 2) and a 2025 Ioniq 5 (generation 3).

fix: Update start_climate for older US Hyundai vehicles

---

requirements.txt
requirements_dev.txt

The latest 3.0 version of cloudscraper released 2 weeks ago solves the Cloudflare blocking. 
However, it's not registered in Pypl yet. 
Trying to get the version through git. 
fix issue: #824

fix: CA login by bumping the cloudscraper version

---

hyundai_kia_connect_api/KiaUvoApiCA.py

Since it seems that HA is unable to correctly retrieve cloudscraper 3.0 from GitHub, the KiaUvoAPICA.py file was modified to use requests for the time being.

fix: KiaUvoApiCA.py Removing cloudscraper

---

hyundai_kia_connect_api/KiaUvoApiEU.py

It looks like Hyundai rolled back authentification methods in EU to previous versions.
Therefore I added some condition to differentiate between Hyundai and Kia/Genesis during Authentication process
Potential fix for https://github.com/Hyundai-Kia-Connect/kia_uvo/issues/1231 and https://github.com/Hyundai-Kia-Connect/hyundai_kia_connect_api/issues/855

fix: Use old login methods for hyundai in EU

---

hyundai_kia_connect_api/KiaUvoApiAU.py

Latest Kia/Hyundai deployments in the AU region have resulted in a change to the  CFBs being used.
They've recompiled libnative-lib.so and changed the IV from iv.ccsp.stamp.au to iv.ccsp.stamp.ap. 
I can also confirm that the actual request flow / content hasn't really changed like we saw with EU. I've done a successful test using bluelink against the NZ server but someone will need to test the AU changes.  I doubt there will be any issues as the process I followed was identical, and I've confirmed that the app id / service id / endpoint addresses are the same by inspecting the APKs.  But if someone in AU could please test these.

fix: Update CFBs for Kia NZ/AU Hyundai AU

---

hyundai_kia_connect_api/KiaUvoApiEU.py

The stable use of `hyundai_kia_connect_api` and Kia Europe is currently only possible with a refresh_token.
This commit fixes `KiaUvoApiEU.py` so that the refresh_token can be used in the password field instead of the Kia password.
This only fixes part of the problem. The part about how to obtain the refresh_token currently still has to be done via a second method.
The test with `pytest` ran successfully. To do this, I set:
```
export KIA_EU_FUATAKGUN_USERNAME="m@m.com"
export KIA_EU_FUATAKGUN_PASSWORD="<REFRESH_TOKEN>"
$ pytest
==================================== test session starts =====================================
platform linux -- Python 3.12.3, pytest-8.4.1, pluggy-1.6.0
rootdir: ../hyundai_kia_connect_api
configfile: setup.cfg
collected 4 items …
```

fix: Partial patch for Kia Europe login

---

hyundai_kia_connect_api/ApiImplType1.py
hyundai_kia_connect_api/KiaUvoApiEU.py

Throw and exception when kia EU login fails for wrong password.  This will get caught by HA and throw the correction exception that triggers re-auth flow.

fix: Exception For auth in Kia EU

---

hyundai_kia_connect_api/ApiImplType1.py
hyundai_kia_connect_api/KiaUvoApiEU.py

Following on from my issue post ([1305](https://github.com/Hyundai-Kia-Connect/kia_uvo/issues/1305)) this PR enables the sensor for charging power to be brought in for more vehicles (confirmed working on 2024 Hyundai Kona EV). Shouldn't interfere with the preexisting code that was working for another user's Ioniq 5.

fix: Accommodate multiple sources for real-time charging power

---

hyundai_kia_connect_api/KiaUvoApiEU.py

97e100b did introduce a bug, as the ev_charging_power will not be populated when the vehicle currently is not charging, e.g. power is 0.

fix(EU): ev_charging_power for EU BEVs

---

hyundai_kia_connect_api/ApiImplType1.py

[PR 903](https://github.com/Hyundai-Kia-Connect/hyundai_kia_connect_api/pull/903/commits/74992962ef2cf47dc16d696e30229ff52a23d3e9) fixed the logic with zero values for ev_charging_power in KiaUvoApiEU.py, but not the identical issue in ApiImplType1.py. This PR just applies the same fix to the latter file.

fix: ev_charging_power for BEVs with power in Green.Electric.SmartGrid
