Hyundai-Kia-Connect/hyundai_kia_connect_api

hyundai_kia_connect_api/utils.py

Corrected and issue impacting 22C Temp. Details here: https://github.com/fuatakgun/kia_uvo/pull/222

fix: Corrected temp range hex

---

hyundai_kia_connect_api/VehicleManager.py

I haven't tested this yet just stood out as I write docs.

fix: corrected method definition

---

hyundai_kia_connect_api/VehicleManager.py
setup.py

Resolves and error that would occur if forced is called before this one.

fix: update cached state on initialize

---

README.rst
requirements.txt
requirements_dev.txt

Fixed vehicle_id <-> all vehicles statement
Added force_refresh_interval details and reference to API Rate Limits

Updated Readme

---

hyundai_kia_connect_api/KiaUvoApiCA.py

Corrected an non fatal error on pin for location.

fix(CA): Corrected PIN location reference

---

hyundai_kia_connect_api/KiaUvoApiCA.py
hyundai_kia_connect_api/Vehicle.py
hyundai_kia_connect_api/const.py

Guessing on the letters used for Canada beyond ICE.  Can't find a record in bluelinky or elsewhere what letter is correct. This is the framework of how other brands will use this field.

feat(CA): Populate Engine Type

---

hyundai_kia_connect_api/KiaUvoApiCA.py
hyundai_kia_connect_api/Vehicle.py
hyundai_kia_connect_api/const.py

Reverts Hyundai-Kia-Connect/hyundai_kia_connect_api#27

Revert "feat(CA): Populate Engine Type"

---

hyundai_kia_connect_api/KiaUvoApiCA.py

fix(CA): Corrected and aligned start types by year and engine type

---

hyundai_kia_connect_api/Vehicle.py

Added the basics for location to vehicle.

feat: Added Location Variables

---

hyundai_kia_connect_api/KiaUvoAPIUSA.py

Credit to @nprez83.   This is the repo that is building the base API that is version 2.0 of the HA integration located here: https://github.com/fuatakgun/kia_uvo/tree/externalAPI

feat(USA Kia): Added Next Service

---

hyundai_kia_connect_api/ApiImpl.py
hyundai_kia_connect_api/HyundaiBlueLinkAPIUSA.py
hyundai_kia_connect_api/KiaUvoApiCA.py
hyundai_kia_connect_api/KiaUvoApiEU.py
hyundai_kia_connect_api/Vehicle.py
hyundai_kia_connect_api/const.py

Added detailed seat status.  This is much easier to do here vs in the custom component.  I haven't run a test of this yet, I also don't have seats that report state to test with.

feat: Added detailed seat status

---

hyundai_kia_connect_api/ApiImpl.py
hyundai_kia_connect_api/KiaUvoApiCA.py
hyundai_kia_connect_api/KiaUvoApiEU.py

Force EU to update location when odometer has changed since last call.   Interested to hear about thoughts on approach on this.  Currently this is using the cached data call to know when to trigger location calls.

feat(EU): Force Location update

---

hyundai_kia_connect_api/KiaUvoApiEU.py

Quick fix - probably not ideal.

fix(EU): Error for missing SOC level

---

hyundai_kia_connect_api/HyundaiBlueLinkAPIUSA.py

Corrected an error that occurs on windows if this is imported.

fix(USA Hyundai): Removed D_T_FMT Import

---

hyundai_kia_connect_api/KiaUvoApiCA.py
hyundai_kia_connect_api/KiaUvoApiEU.py

feat(EU): add setting charge limits

---

hyundai_kia_connect_api/ApiImpl.py
hyundai_kia_connect_api/KiaUvoApiEU.py
hyundai_kia_connect_api/VehicleManager.py

I realized that force update is not implemented or at least does not update any internal state. This implements the forced update
by first retrieving either the cached state or the full forced state (as bluelinky does) and then updates the internal properties from the pieced-together dict.
It also implements a `_get_location` method, cdnninjas is more fleshed out though

fix(EU): force update

---

hyundai_kia_connect_api/VehicleManager.py

Trust that within the API if a force is done it updates state.   This is for sure implemented in EU and CA.  USA may require work.

fix: Reduce API Calls

---

hyundai_kia_connect_api/KiaUvoApiEU.py
hyundai_kia_connect_api/utils.py
tests/eu_login_test.py

fix(EU): Corrected force update

---

hyundai_kia_connect_api/HyundaiBlueLinkAPIUSA.py

For https://github.com/fuatakgun/kia_uvo/issues/397

feat(USA Hyundai): Add Washer Fluid and Key Battery

---

hyundai_kia_connect_api/HyundaiBlueLinkAPIUSA.py
hyundai_kia_connect_api/KiaUvoAPIUSA.py
hyundai_kia_connect_api/KiaUvoApiCA.py
hyundai_kia_connect_api/KiaUvoApiEU.py
hyundai_kia_connect_api/Vehicle.py

BREAKING CHANGE:  Renamed distance based attribute to range to better reflect what they are

fix: rename distance to range

---

hyundai_kia_connect_api/HyundaiBlueLinkAPIUSA.py

https://github.com/fuatakgun/kia_uvo/issues/397

fix(USA Hyundai): DTE Blank

---

hyundai_kia_connect_api/KiaUvoApiEU.py

https://github.com/fuatakgun/kia_uvo/issues/424

fix(EU): Force Update is missing update time

---

hyundai_kia_connect_api/HyundaiBlueLinkAPIUSA.py

Replicates https://github.com/fuatakgun/kia_uvo/pull/347
Resolves https://github.com/fuatakgun/kia_uvo/issues/446

fix(Hyundai USA): Switch lock attribute

---

hyundai_kia_connect_api/KiaUvoApiEU.py

Credit goes to https://github.com/Hyundai-Kia-Connect/hyundai_kia_connect_api/issues/140 @zulufoxtrot for finding this!

fix(EU): Force Refresh Using wrong token

---

hyundai_kia_connect_api/KiaUvoApiEU.py
hyundai_kia_connect_api/exceptions.py

Continued work from https://github.com/Hyundai-Kia-Connect/hyundai_kia_connect_api/pull/83
- Add API exceptions
- Perform API error handling
- Refactor: simplify headers
- Linting
Passed tests:
- cached request
- forced request
- stop climate
- stop charging

(Kia EU) API Error handling + refactor

---

hyundai_kia_connect_api/VehicleManager.py

To assist with https://github.com/fuatakgun/kia_uvo/issues/450#issuecomment-1326782443.
I suspect this is a unit or time zone issue.

fix: Logging and reduce calls

---

README.rst
hyundai_kia_connect_api/VehicleManager.py

fix: Debug logs differential

---

hyundai_kia_connect_api/KiaUvoAPIUSA.py

Starting to adjust this region to fit the same model we are using in other regions. Force update still needs work but this moves it forward.  Untested as I don't have someone who can do that for USA.

refactor(USA KIA): Adjust to fit the same model

---

hyundai_kia_connect_api/KiaUvoApiEU.py
hyundai_kia_connect_api/Vehicle.py

Driving stats, Continued work from https://github.com/Hyundai-Kia-Connect/hyundai_kia_connect_api/pull/107
It works but I'm not sure about the implementation.
I kind of hacked the current implem: used a dataclass to store a day, then put that object into the dict returned by _get_driving_info. Not very clean but I don't see how to do it better without refactoring the whole thing.
I also don't know if/how it works with other regions. Tested on Kia EU only.
Feel free to suggest changes.
Preview of the data on Grafana:

Feat: driving stats

---

hyundai_kia_connect_api/ApiImpl.py
hyundai_kia_connect_api/KiaUvoApiEU.py
hyundai_kia_connect_api/VehicleManager.py
hyundai_kia_connect_api/const.py

Unable to test this as I am not in the EU.  I also don't have an EV.

feat(EU): Charge Port Action

---

hyundai_kia_connect_api/KiaUvoApiEU.py

Fixed an issue where some cars wouldn't show DTE.   This depends on the model where it places the data. Resolves https://github.com/Hyundai-Kia-Connect/kia_uvo/issues/475

fix(EU): Two Potential DTE Locations

---

hyundai_kia_connect_api/KiaUvoApiEU.py

Issue that impacts force update calling over and over.

fix(EU): Last updated typo

---

hyundai_kia_connect_api/KiaUvoApiEU.py

Resolves. https://github.com/Hyundai-Kia-Connect/kia_uvo/issues/475

fix(EU): DTE Not Showing

---

hyundai_kia_connect_api/KiaUvoApiEU.py

Added Fuel level and washer fluid level

feat(EU): Additional Sensors

---

hyundai_kia_connect_api/KiaUvoApiEU.py

Dec update is causing odometer to report 0 which makes it not update.

fix(EU): Show odometer if 0

---

hyundai_kia_connect_api/KiaUvoApiEU.py
hyundai_kia_connect_api/Vehicle.py

Add Target range SOC to vehicle

feat(EU): Target SOC range

---

hyundai_kia_connect_api/KiaUvoApiCA.py

The purpose of this PR is to fix an issue with certain vehicles (Hyundai CA) returning last_updated_at values in their own timezone rather than UTC.
When KiaUvoApiCA.force_refresh_vehicle_state is called, we compare the last_updated_at value from the vehicle with current system time and set a custom timezone to account for the offset, if any. Once the custom timezone is set, the offset will be zero for subsequent calls to force_refresh_vehicle_state.
Tested and working for Hyundai CA.

fix(Hyundai CA): calculate and set timezone based on Vehicle setting

---

hyundai_kia_connect_api/KiaUvoAPIUSA.py

Resolves https://github.com/Hyundai-Kia-Connect/kia_uvo/issues/504

fix(KIA USA): Failed force update

---

hyundai_kia_connect_api/KiaUvoApiCA.py

Set defaults for an EV to prevent error

feat(CA): Set Defaults for Seats

---

hyundai_kia_connect_api/KiaUvoAPIUSA.py
hyundai_kia_connect_api/KiaUvoApiCA.py
hyundai_kia_connect_api/Vehicle.py

feat:  DTC Count and Kia USA cleanup

---

hyundai_kia_connect_api/KiaUvoApiEU.py
hyundai_kia_connect_api/Vehicle.py

Still need to adjust typing before merging for time before merging.  Not sure if a better way exists to represent day of week.

feat(EU): Get Charge Schedules

---

hyundai_kia_connect_api/KiaUvoAPIUSA.py

fix(USA Kia):  Variety of errors

---

hyundai_kia_connect_api/KiaUvoApiEU.py

https://github.com/Hyundai-Kia-Connect/kia_uvo/issues/539  @fuatakgun

fix(EU): AMPM Time for Charging

---

hyundai_kia_connect_api/ApiImpl.py
hyundai_kia_connect_api/KiaUvoAPIUSA.py
hyundai_kia_connect_api/VehicleManager.py

https://github.com/Hyundai-Kia-Connect/kia_uvo/issues/540

fix(USA KIA): Refresh Vehicles if Call Fails

---

hyundai_kia_connect_api/KiaUvoApiEU.py

https://github.com/Hyundai-Kia-Connect/kia_uvo/issues/537 please review @fuatakgun  this is to fix some strange data issues in the EU.

fix(EU): Resolve non standard time

---

hyundai_kia_connect_api/KiaUvoApiEU.py

Round range remaining to 2 decimal places.

fix(EU): Round Ranges to 2 Decimal

---

hyundai_kia_connect_api/KiaUvoAPIUSA.py

https://github.com/Hyundai-Kia-Connect/kia_uvo/issues/543

fix(USA Kia): Charging Mapping

---

hyundai_kia_connect_api/KiaUvoAPIUSA.py

https://github.com/Hyundai-Kia-Connect/kia_uvo/issues/543

feat(KIA USA): SOC Level

---

hyundai_kia_connect_api/HyundaiBlueLinkAPIUSA.py

https://github.com/Hyundai-Kia-Connect/kia_uvo/issues/515

fix(USA Hyundai): Air Temp Units

---

hyundai_kia_connect_api/Vehicle.py
hyundai_kia_connect_api/VehicleManager.py

BREAKING CHANGE:  No longer scans on initial setup in case a car needs to be disabled.

feat: Enable and Disable Cars

---

hyundai_kia_connect_api/VehicleManager.py
tests/ca_login_test.py
tests/eu_login_test.py

BREAKING CHANGE:  Individual vehicle update calls now use vehicle.id instead of vehicle.

fix: Align command types

---

hyundai_kia_connect_api/KiaUvoApiEU.py

Catch error in response from get device.  Add the error code provided that appears to be a timeout of sorts.
https://github.com/Hyundai-Kia-Connect/kia_uvo/issues/553

fix(EU): Device error 9999

---

hyundai_kia_connect_api/KiaUvoAPIUSA.py

https://github.com/Hyundai-Kia-Connect/kia_uvo/issues/572

fix(USA Kia):  EV Fuel Range

---

hyundai_kia_connect_api/ApiImpl.py
hyundai_kia_connect_api/HyundaiBlueLinkAPIUSA.py
hyundai_kia_connect_api/KiaUvoApiCA.py
hyundai_kia_connect_api/KiaUvoApiEU.py

Ignore bad API data when value is over 100%.

fix(CA): Only report SOC under 100 Percent

---

hyundai_kia_connect_api/HyundaiBlueLinkAPIUSA.py
hyundai_kia_connect_api/KiaUvoAPIUSA.py
hyundai_kia_connect_api/KiaUvoApiCA.py
hyundai_kia_connect_api/KiaUvoApiEU.py
hyundai_kia_connect_api/Vehicle.py

feat: Window Status

---

tests/ca_login_test.py

currently the test fails even though code works when run locally.

chore: Remove CA login test for now

---

setup.py

Hi,
the setup.py file is missing a lot of the requirements from requirements.txt. I updated the code to include all the requirements from requirements.txt.

fix: add requirements from requirements.txt

---

hyundai_kia_connect_api/KiaUvoApiEU.py

This fixes the integration in Home Assistant for my Hyundai Ioniq

Fix Hyundai login EU

---

README.rst

fix: Force Release for EU Login fix

---

MANIFEST.in
setup.py

This should fix the issue when building wheels.

fix: use requirements.txt for requirements in setup (#316)

---

hyundai_kia_connect_api/KiaUvoApiCA.py

Added fuel level for Canada. Resolves https://github.com/Hyundai-Kia-Connect/kia_uvo/issues/630

feat(CA): Fuel Level

---

hyundai_kia_connect_api/HyundaiBlueLinkAPIUSA.py

https://github.com/Hyundai-Kia-Connect/kia_uvo/issues/644

fix(USA Hyundai):  exception if data not returned

---

hyundai_kia_connect_api/KiaUvoApiEU.py

Added local stamp generation for EU as discussed on discord.

feat(EU): local stamp generation #370

---

hyundai_kia_connect_api/KiaUvoApiEU.py

Reverting a mistake I made earlier.

fix: Corrected cfb location

---

hyundai_kia_connect_api/KiaUvoApiEU.py

Currently errors for me with a fake username password but initial steps are successful so this needs to be tested by someone with a valid account.

fix(Genesis):  Correct port

---

hyundai_kia_connect_api/KiaUvoApiEU.py
hyundai_kia_connect_api/exceptions.py

Adjust Device ID error to be API error as it isn't directly auth.

fix:  Adjust device ID error and fix url error

---

hyundai_kia_connect_api/KiaUvoApiAU.py

Also (maybe) fixes "actions" which required more authentication with the PIN, they were previously using the wrong headers.

fix(AUS): return location correctly

---

hyundai_kia_connect_api/KiaUvoAPIUSA.py

fix: Kia USA Handle low/high air temp values

---

hyundai_kia_connect_api/ApiImpl.py
hyundai_kia_connect_api/KiaUvoApiAU.py
hyundai_kia_connect_api/VehicleManager.py
hyundai_kia_connect_api/__init__.py
hyundai_kia_connect_api/const.py

Tested on my Ioniq 6 and seems to work well (minus the whole device ID invalidation thing which is unrelated)

feat: add support for opening and closing windows

---

README.rst

Forcing a build but also fixing some docs at the same time.

fix(EU): Add 12h using datetime

---

hyundai_kia_connect_api/HyundaiBlueLinkAPIUSA.py

Change data for EV climate start to match sniffed data from iOS app

fix(USA): Change Climate Data for EV

---

hyundai_kia_connect_api/KiaUvoApiEU.py

Attempt to solve device ids being invalid.

fix(EU): invalid device id

---

hyundai_kia_connect_api/KiaUvoApiEU.py

fix(EU): Driving Info Error

---

hyundai_kia_connect_api/KiaUvoApiEU.py

https://github.com/Hyundai-Kia-Connect/kia_uvo/issues/609

fix(EU):  english fall back warning

---

hyundai_kia_connect_api/KiaUvoAPIUSA.py

i dont know how to properly test this. but I am 99.999% confident this is good.
i did test this with curl, so I know the API json data is correct and works.

adding function for heat/ventilated seats in USA region

---

README.rst

feat(USA): Kia seat support

---

.github/workflows/lintPR.yaml

Adding missing semantic title check

chore: semantic title check

---

hyundai_kia_connect_api/KiaUvoApiEU.py

Fixed Window front left/right (not tested)

fix(EU): window status

---

hyundai_kia_connect_api/KiaUvoApiEU.py

@cdnninja [hyundai_kia_connect_monitor](https://github.com/ZuinigeRijder/hyundai_kia_connect_monitor#introduction-hyundai_kia_connect_monitor) uses Property Vehicle.location_last_updated_at. A German Kona model 2024 user tried out the support of the new EU models (v3.13.0). 
Property Vehicle.location_last_updated_at was not given back a datetime for the EU new models (e.g. Kia EV9, Hyundai Kona 2024 model) but a dictionary. Converted the dictionary to a datetime, like this is done for the other EU models.
Vehicle._location_last_set_time is now also converted to a datetime for the EU new models.
Other improvements:
- all the supported languages list are two-letters, so no distinguishing of e.g. en-gb or en-us, so just use the first two letters to avoid errors
- fixed style warning: …

fix(EU): New models, convert location_last_updated_at to datetime

---

hyundai_kia_connect_api/Vehicle.py

Should fix the kia_uvo problem: Not valid unit for device class distance #812

fix: Distance unit fixed

---

hyundai_kia_connect_api/KiaUvoApiAU.py

@bitnimble  FYI if you create a pull first before merging it will auto fix any black formatting issues.  Other checks also come in helpful.

chore(AU): black fixes

---

hyundai_kia_connect_api/KiaUvoAPIUSA.py

The PR fixes [issue 478](https://github.com/Hyundai-Kia-Connect/hyundai_kia_connect_api/issues/478) the SSL signature failure for KIA USA.

fix(USA):  ssl signature

---

hyundai_kia_connect_api/KiaUvoApiAU.py

Solves an issue that can cause faults.

fix(AU):  Time logic for certain python versions

---

hyundai_kia_connect_api/ApiImpl.py

https://github.com/Hyundai-Kia-Connect/kia_uvo/issues/853

fix: check for location before geocode update

---

hyundai_kia_connect_api/ApiImplType1.py

Fixes https://discord.com/channels/652755205041029120/669318980334387215/1223447578817986560

fix: parse ccs2 last_updated_at as UTC instead of local timezone

---

hyundai_kia_connect_api/KiaUvoApiEU.py

fix: use ccu_css support for all headers

---

hyundai_kia_connect_api/KiaUvoAPIUSA.py
requirements.txt

fix: USA ssl connection by importing certs from certifi
Update KiaUvoAPIUSA.py
After doing more research, it was the heatedventedseat option that cause the issue. Added a if statement to only include the block if passed to start climate

fix: usa hyundai remote start fails

---

hyundai_kia_connect_api/KiaUvoApiCA.py

Adds synchronicity (run until complete) and returns OrderStatus instead of simply returning True.

fix: KiaUVOApiCA check_action_status

---

hyundai_kia_connect_api/ApiImplType1.py
hyundai_kia_connect_api/HyundaiBlueLinkAPIUSA.py
hyundai_kia_connect_api/KiaUvoApiAU.py
hyundai_kia_connect_api/KiaUvoApiCN.py
hyundai_kia_connect_api/KiaUvoApiEU.py
hyundai_kia_connect_api/Vehicle.py

See this issue: https://github.com/Hyundai-Kia-Connect/hyundai_kia_connect_api/issues/617#issuecomment-2315105745

fix: set daily_stats distance_unit

---

hyundai_kia_connect_api/HyundaiBlueLinkAPIUSA.py

Implement in HyundaiBlueLinkAPIUSA.py update_month_trip_info() and update_day_trip_info().
Fill vehicle.month_trip_info and vehicle.day_trip_info, instead of only vehicle.daily_stats for HyundaiBlueLinkAPIUSA.py.
Note that I used a trick to avoid calling GET /ac/v2/ts/alerts/maintenance/evTripDetails each time, by storing the state in vehicle.data["filled_trips"].
See this issue: https://github.com/Hyundai-Kia-Connect/hyundai_kia_connect_api/issues/617#issuecomment-2334247887
Thereafter this issue can probably closed.

feat: implement vehicle.month_trip_info and vehicle.day_trip_info for Hyundai USA Bluelink

---

hyundai_kia_connect_api/ApiImplType1.py

Sometimes EU reports old time stamps
https://github.com/Hyundai-Kia-Connect/kia_uvo/issues/931

fix: handle EU server time issue

---

hyundai_kia_connect_api/ApiImplType1.py
hyundai_kia_connect_api/Vehicle.py

Workaround for https://github.com/Hyundai-Kia-Connect/kia_uvo/issues/931

fix(EU): handle EU server time issue workaround

---

hyundai_kia_connect_api/Vehicle.py

Small improvement: make sure that the new latest_updated_at is newer than the previous latest_updated_at.

fix(EU): handle EU server time issue workaround small improvement

---

hyundai_kia_connect_api/Vehicle.py

https://github.com/Hyundai-Kia-Connect/kia_uvo/issues/946

fix: geocode error

---

hyundai_kia_connect_api/ApiImpl.py
hyundai_kia_connect_api/KiaUvoApiEU.py
hyundai_kia_connect_api/VehicleManager.py

https://github.com/Hyundai-Kia-Connect/kia_uvo/issues/957
Attempting to add new "Hazards" and "Hazards and Horn" feature. My first contribution so will likely need some help getting it release-worthy.
@cdnninja @asychow 🙏

feat(EU): support new hazard lights and horn features

---

README.rst
hyundai_kia_connect_api/bluelink.py
setup.py

The tool `bluelink` dumps information live from the API and optionally stores it locally to JSON. This makes iterating on features much easier.
I had to work around Vehicle class idiosyncrasies. Not changing this class as it would be a significant breaking change.

feat: implement script 'bluelink'

---

README.rst

https://github.com/Hyundai-Kia-Connect/hyundai_kia_connect_api/actions/runs/11872830215/job/33086994062
https://github.com/Hyundai-Kia-Connect/hyundai_kia_connect_api/actions/runs/11880418213/job/33103539988

fix: Fix pypi release error

---

hyundai_kia_connect_api/ApiImpl.py
hyundai_kia_connect_api/KiaUvoApiUSA.py

relates to PR: https://github.com/Hyundai-Kia-Connect/kia_uvo/pull/1010

feat: Adds steeringWheel option separate from options.heating

---

hyundai_kia_connect_api/KiaUvoApiEU.py
hyundai_kia_connect_api/const.py

#564   Makes it less noisy on breaking kia_uvo.

fix: remove exception on last action tracking

---

hyundai_kia_connect_api/KiaUvoApiCA.py

revert back to SPA from CWP because it will break location. However, with client id and client secret, login was successful with SPA and the token does not expire after 10 mins. 
Updated expiration time from hardcoded into expiredIn returned from server.

fix(CA): login issue

---

hyundai_kia_connect_api/bluelink.py

Add indentation to JSON output file output for readability

style: Add indentation to JSON output file output for readability

---

hyundai_kia_connect_api/KiaUvoApiCA.py

-EV9 KIA.
https://github.com/Hyundai-Kia-Connect/hyundai_kia_connect_api/pull/749

fix(CA): Trying to revert change to climate command for non EV9

---

hyundai_kia_connect_api/ApiImplType1.py
hyundai_kia_connect_api/KiaUvoApiAU.py
hyundai_kia_connect_api/KiaUvoApiEU.py

#729 Align lock action to details provided and EU.

fix(AU): Lock action

---

hyundai_kia_connect_api/ApiImpl.py
hyundai_kia_connect_api/ApiImplType1.py
hyundai_kia_connect_api/VehicleManager.py

#729  add vehicle to load support.

feat: Vehicle to load

---

hyundai_kia_connect_api/HyundaiBlueLinkApiUSA.py
hyundai_kia_connect_api/KiaUvoApiAU.py
hyundai_kia_connect_api/KiaUvoApiCA.py
hyundai_kia_connect_api/KiaUvoApiEU.py
hyundai_kia_connect_api/KiaUvoApiUSA.py

Remove spots that log tokens.   People tend to post these online.

fix: remove token logging

---

hyundai_kia_connect_api/ApiImplType1.py

Updated V2L location to get state

fix: V2l for CCS vehicles

---

hyundai_kia_connect_api/ApiImplType1.py
hyundai_kia_connect_api/KiaUvoApiIN.py

Support climate start/stop service for Indian Region

feat: Add climate support for Indian Region 

---

hyundai_kia_connect_api/KiaUvoApiCA.py

This PR adds support for Canadian Hyundai EVs to grab their Trip statistics. The method used is mostly grabbed from the USA bluelink file.
Tested on a 2024 Ioniq 6.

feat: Support Trip details for Daily Stats for Canadian cars.

---

hyundai_kia_connect_api/KiaUvoApiCA.py

This PR try to fix login for Canada.
https://github.com/Hyundai-Kia-Connect/kia_uvo/issues/1140

fix: CA login

---

hyundai_kia_connect_api/KiaUvoApiIN.py

Tested locally using bluelink tool and works fine!
Requesting PR review - 
@cdnninja

feat: added Kia India Support

---

hyundai_kia_connect_api/KiaUvoApiUSA.py
hyundai_kia_connect_api/utils.py

See https://github.com/Hyundai-Kia-Connect/hyundai_kia_connect_api/issues/825

fix: date parsing and update AppVersion in headers

---

hyundai_kia_connect_api/ApiImplType1.py

fix:  Start climate error in multiple regions

---

hyundai_kia_connect_api/KiaUvoApiCA.py

Add deviceId to login call as discussed here https://github.com/Hyundai-Kia-Connect/kia_uvo/issues/1163#issuecomment-3092457705

fix(CA): Add deviceId to login call

---

hyundai_kia_connect_api/KiaUvoApiEU.py

fix:  EU Hyundai Login

---

hyundai_kia_connect_api/KiaUvoApiCA.py
requirements.txt
requirements_dev.txt

Try to fix Hyundai Canada problem without the use of cloudscraper 3.0.0

fix: Hyundai Canada problem without CloudScraper

---

tests/eu_login_test.py

https://github.com/Hyundai-Kia-Connect/hyundai_kia_connect_api/pull/877

chore: disable login tests for EU

---

hyundai_kia_connect_api/KiaUvoApiUSA.py

https://github.com/Hyundai-Kia-Connect/kia_uvo/issues/1312

feat: USA Kia Sunroof and charge power

---

hyundai_kia_connect_api/ApiImplType1.py

fix(EU): access token hyundai error
